### ISSUE TITLE
how to control the gripper when load_gripper set to true?

### ISSUE THREAD

**Issue by xuzhiiii** [rail-berkeley/serl_franka_controllers#7]
thanks for your great project, very helpful for me and I can control real franka with little ROS knowledge.

but I don't know how to add gripper control to it...which "geometry_msgs.msg" could used to control the gripper and how?

**Comment by charlesxu0124** [comment]
If you are using a Franka gripper, take a look at [franka_gripper_server.py](https://github.com/rail-berkeley/serl/blob/main/serl_robot_infra/robot_servers/franka_gripper_server.py). It contains all the topics and messages you need to send gripper commands and view gripper state.

**Comment by xuzhiiii** [comment]
Thank you again for your detailed response. REALLY appreciate your time and this significant project.
