### ISSUE TITLE
How to control the franka gripper close with force?

### ISSUE THREAD

**Issue by yuzej** [rail-berkeley/serl_franka_controllers#8]
I analysis the test.py and write a class file to execute RL with franka robot.
One action is to close the gripper and grasp the object
I define the function like the img. The width is good, but the grasp force is so small, less than 10N, and the object is falling down.
What should I do to enhance the grasp force?
![image](https://github.com/user-attachments/assets/479aec3b-3a2c-4781-8025-7719a8614373)

**Comment by charlesxu0124** [comment]
Hello, you can simply set `goal.force` to a higher value. I used 130 in my projects.
