### ISSUE TITLE
Random Intense Movement Right After Launching the Impedance Controller

### ISSUE THREAD

**Issue by c-yiting** [rail-berkeley/serl_franka_controllers#9]
Hi, thanks a lot for this repository!

system environment:
1. ROS Noetic
2. franka-ros 0.10.1 and libfranka 0.9.2

Lightweight customed fingers are mounted to replace the original fingers on the panda gripper. 

After I run the suggested command to launch the impedance controller:
`roslaunch serl_franka_controllers impedance.launch robot_ip:=<RobotIP> load_gripper:=true
`
Without any further input, the robot moves randomly and intensely right after 
`Started controllers: cartesian_impedance_controller`
 with the following error:
`[ERROR]: libfranka: Move command aborted: motion aborted by reflex! ["power_limit_violation"]`
`control_command_success_rate: 1`

Then the robot is running in high-stiffness.

Any ideas on solving this issue? Thanks!

**Comment by jianlanluo** [comment]
Hi, you mentioned your new finger is lightweight, so perhaps you need to recalibrate your payload on franka server

**Comment by charlesxu0124** [comment]
Hello, sorry to hear that your robot is acting in such a scary way. I've never experienced this issue before. The power_limit_violation is usually a result of a high torque command, and the high-stiffness afterwards is a result of the Franka's internal safety mechanism stopping the arm after the power limit violation.

Do you mind sharing the entire terminal log and maybe a picture of your arm configuration so I can try to investigate the issue further?

**Comment by jianlanluo** [comment]
so if your payload is too lightweight and isn't calibrated; the gravity compensation torques will drive your robot crazy
